<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25310" started-at="2020-02-13T18:22:07Z" finished-at="2020-02-13T18:22:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25310" started-at="2020-02-13T18:22:07Z" finished-at="2020-02-13T18:22:32Z">
      <class name="TestPage.HomePageTest">
        <test-method status="FAIL" signature="verifyEmail()[pri:0, instance:TestPage.HomePageTest@4b741d6d]" name="verifyEmail" duration-ms="353" started-at="2020-02-13T18:22:07Z" finished-at="2020-02-13T18:22:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed to verify expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed to verify expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at TestPage.HomePageTest.verifyEmail(HomePageTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmail -->
        <test-method status="PASS" signature="verifyTabs()[pri:0, instance:TestPage.HomePageTest@4b741d6d]" name="verifyTabs" duration-ms="506" started-at="2020-02-13T18:22:07Z" finished-at="2020-02-13T18:22:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTabs -->
        <test-method status="PASS" signature="verifyUrl()[pri:0, instance:TestPage.HomePageTest@4b741d6d]" name="verifyUrl" duration-ms="24303" started-at="2020-02-13T18:22:08Z" finished-at="2020-02-13T18:22:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUrl -->
      </class> <!-- TestPage.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
